name: mln_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

resolution: workspace
dependencies:
  mln_shared: ^1.0.0
  nyxx: ^6.7.0
  nyxx_commands: ^6.0.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4

