name: mln_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

resolution: workspace
dependencies:
  collection: ^1.19.1
  html: ^0.15.6
  http: ^1.5.0
  mln_shared: ^1.0.0
  nyxx: ^6.7.0
  nyxx_commands: ^6.0.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  xml: ^6.6.1

dependency_overrides:
  # Allows named functions to be compiled.
  # See: https://github.com/nyxx-discord/nyxx_commands/pull/169
  nyxx_commands:
    git:
      url: https://github.com/Levi-Lesches/nyxx_commands
      ref: id-func-name
