name: construction
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  mln_shared: ^1.0.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.3
