name: mln_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

resolution: workspace
dependencies:
  xor_dart: ^1.0.2
  uuid: ^4.5.1
  http: ^1.4.0
  collection: ^1.19.1
  shelf: ^1.4.2
  xml: ^6.5.0
  http_status_code: ^0.0.2
