name: xor_dart
description: Simple XOR symmetric encryption/decryption cipher with or without a secret key
version: 1.0.2
repository: https://github.com/isaacselement/xor.dart
homepage: https://github.com/isaacselement/xor.dart

resolution: workspace
environment:
  sdk: ^3.7.0

dev_dependencies:
  lints:
  test:
